### ISSUE TITLE
stickynav on map goes out of it's bounds

### ISSUE THREAD

**Issue by dbriksza** [Lambda-School-Labs/city-data-comparison-fe#138]
Rare bug that I've gotten once or twice, not sure how to duplicate but I know it only happens if you've been on the page a while. 
![Capture](https://user-images.githubusercontent.com/29048332/73252076-23c9b200-4188-11ea-99ce-7740a0bd82af.PNG)

**Comment by dbriksza** [comment]
I just recreated this while resizing my window

**Comment by michaelharms6010** [comment]
#148 should fix this. needs testing.
