### ISSUE TITLE
Profile Img doesn't update on login

### ISSUE THREAD

**Issue by dbriksza** [Lambda-School-Labs/city-data-comparison-fe#142]
When the user logs in using google or linkedin the avatar in the top right corner is displayed as default until the page reloads

**Comment by dbriksza** [comment]
![Capture](https://user-images.githubusercontent.com/29048332/73300960-e85ad200-41df-11ea-8231-c4e9defe0981.PNG)

**Comment by michaelharms6010** [comment]
#148 fixes this, but needs testing
