### ISSUE TITLE
Mobile Datadisplay is "All Kinds of Messed Up"

### ISSUE THREAD

**Issue by michaelharms6010** [Lambda-School-Labs/city-data-comparison-fe#70]
This ticket is a placeholder to describe the issue and potential solutions

The Map page is facing a large refactor - I think it's best to consider fixing mobile view "blocked" until Map page restructuring is done

**Comment by dbriksza** [comment]
Specifically there is an issue with the graphs growing in size forever until the site crashes. Steps to recreate: open Safari on iPhone and navigate to citrics.io.  Go to map page and select any city. Select any metric to view.
![81977862_556949688223462_6558055606589063168_n](https://user-images.githubusercontent.com/29048332/72381032-a6f8fb80-36e4-11ea-8739-58f107ee6ed2.jpg)
![82628110_1254344031620760_4734040947971588096_n](https://user-images.githubusercontent.com/29048332/72381033-a6f8fb80-36e4-11ea-96c4-b6c10cb8e4f6.jpg)

**Comment by michaelharms6010** [comment]
With the map/datadisplay redesigned we can probably start to focus on this ticket

**Comment by michaelharms6010** [comment]
#158 has likely fixed this; let's evaluate tomorrow. Barring any unexpected results, this ticket can be closed.

**Comment by michaelharms6010** [comment]
I believe this is fixed.
