### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by theJOHNwatt** [Lambda-School-Labs/city-data-comparison-fe#77]
Creating profile component based off Ruths design and using CRUD functions from our backend.

**Comment by michaelharms6010** [comment]
Avatar upload needs debugging
Favorites display form still needs testing

**Comment by michaelharms6010** [comment]
This ticket can be closed when avatar uploading is consistently smooth

**Comment by michaelharms6010** [comment]
I lied - this can be closed when mobile styling is complete

**Comment by theJOHNwatt** [comment]
styling complete
