### ISSUE TITLE
Slight text move on focus

### ISSUE THREAD

**Issue by dbriksza** [Lambda-School-Labs/city-data-comparison-fe#83]
The text moves slightly when the button is hovered- not sure if this is intentional or even a big deal but I it irks me
https://gyazo.com/2ad33f8672d0476dfa6d7d1a54db8165

**Comment by dbriksza** [comment]
It's on multiple parts of the page- probably related to a class then https://gyazo.com/b74303e8e451b5d2761f67bed23b6764

**Comment by michaelharms6010** [comment]
Has this been resolved? Can this ticket be closed?
